# Generated by Django 3.2.9 on 2022-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prepopulate_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
            ],
        ),
    ]
